config/routes.rb
Rails.application.routes.draw do
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'products#index'

  resources :users
  resources :categories
  resources :products
  resources :carts
  resources :cart_products

end

app/models/cart_product.rb
class CartProduct < ActiveRecord::Base
  validates :quoted_price, :quantity, presence: true
  belongs_to :product
  belongs_to :cart

end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  before_action :logged_in?
  # before_action :authorize, only: [:index]

  include CartProductsHelper

  def index
    redirect_to root_path
  end

  def new
    puts params
    if create_cart_product
      redirect_to root_path
    else
      render 'new'
    end
  end

  def create
  end

  def show
    find_cart_product
  end

  def edit
    find_cart_product
  end

  def update
    find_cart_product
    if update_cart_product
      redirect_to action: "index"
    else
      render 'edit'
    end
  end

  def destroy
    delete_cart_product
    redirect_to action: "index"
  end
end

app/helpers/cart_products_helper.rb
module CartProductsHelper

include CartsHelper

  def all_cart_products
    @cart_products = CartProduct.all
  end

  def new_cart_product
    @cart_product = CartProduct.new
  end

  def create_cart_product
    @cart_product = CartProduct.new
    @cart_product.cart_id = current_cart.id
    @cart_product.product_id = cart_product_params[:product_id]
    @cart_product.quantity = cart_product_params[:quantity] || 1
    @cart_product.quoted_price = @cart_product.product.price
    @cart_product.save
  end

  def find_cart_product
    @cart_product = CartProduct.find(params[:id])
  end

  def update_cart_product
    @cart_product.update(cart_product_params)
  end

  def delete_cart_product
    find_cart_product
    @cart_product.destroy
  end

  private

    def cart_product_params
      return params.permit(:product_id, :id, :cart_id, :user_id, :quoted_price, :quantity) unless params[:cart_product]
      params.require(:cart_product).permit(:id, :product_id, :cart_id, :user_id, :quoted_price, :quantity)
    end

end

app/views/cart_products/_form.html.erb
<%= form_for @cart_product do |f| %>

  <% if @cart_product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@cart_product.errors.count, "error") %> prohibited
        this cart_product from being saved:
      </h2>
      <ul>
        <% @cart_product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/cart_products/edit.html.erb
<h1>Editing <%=@cart_product.id%></h1>

<%= render 'form' %>

<%= link_to 'Back', cart_products_path %>
<%=link_to 'Delete', cart_product_path, method: :delete, data: { confirm: "Delete #{@cart_product.id}?"}%>

app/views/cart_products/index.html.erb
<% @cart_products.each do |cart_product| %>
    <em><%=cart_product.id %> </em>
    <b><%= link_to "Edit", edit_cart_product_path(cart_product.id) %></b>
    <b><%=link_to 'Delete', cart_product_path(cart_product.id), method: :delete, data: { confirm: "Delete #{cart_product.id}?"}%></b>
    <br>
<%end%>
    <b><%= link_to "Add cart_product", new_cart_product_path %></b>

app/views/cart_products/show.html.erb
<div class="product-show-container">
<h2><%=@product.name%></h2>
<div class="product-detail-container">
<img class="well" src="<%=@product.image%>"></img>
<ul>
  <%="Stock: #{@product.stock}"%><br>
  <%= "Price: $#{@product.price}" %>
  <br><button class="cartbtn" id="<%=@product.id%>">Add to Cart</button>
</ul>
</div>
<div class="nav navbar">
<% if admin? %>
    <li><%= link_to 'Edit', edit_product_path %></li>
    <li><%=link_to 'Delete', product_path, method: :delete, data: { confirm: "Delete #{@product.name}?"}%></li>
<%end%>
    <li><%= link_to 'Home', root_path %></li>
  </div>
</div>