config/routes.rb
Rails.application.routes.draw do
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'products#index'

  resources :users
  resources :categories
  resources :products
  resources :carts
  resources :cart_products

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, uniqueness: true
  validates :first_name, :last_name, :username, :password, presence: true

  has_many :active_carts, -> { where "order_id = NULL" }, class_name: "Cart"
  has_many :ordered_carts, -> { where "order_id != NULL" }, class_name: "Cart"
  has_many :products_in_cart, through: :active_carts, class_name: "CartProduct"
  has_many :products_ordered, through: :ordered_carts, class_name: "CartProduct"
  has_many :addresses
  has_many :financial_informations

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def create
    user = User.new(user_params)
    user.title = 'user'
    user.title = 'admin' if user.username == 'jon' || user.username == 'mia'
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(id: user.id)
    else
      render 'new'
    end
  end

  def new
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def show
    unless session[:user_id]
      redirect_to login_path
    end
    @user = User.find(params[:id])
    @products = Product.all
    render 'show'
  end

  def update
    user = User.find(session[:user_id])
    if user.update(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(session[:user_id])
    user.delete
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:username, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UsersHelper

  before_action :logged_in?, except: [:new, :create]
  before_action :authorize, except: [:new, :create, :edit, :update, :destroy]

  def index
    all_users
  end

  def create
    @user = User.new(user_params)
    @user.admin = false
    if @user.save
      session[:user_id] = @user.id
      redirect_to users_path(id: @user.id)
    else
      render 'new'
    end
  end

  def new
    new_user
  end

  def edit
    puts "admin status is #{admin?}"
    puts "login status is #{logged_in?}"
    redirect_to action: "index" if admin?
    find_user
  end

  def show
    current_user
  end

  def update

    redirect_to user_path and return unless current_user.id == params[:id]
    user = User.find(session[:user_id])
    if user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    find_user
    @user.delete if @user == current_user  || admin?
    redirect_to root_path unless admin?
    redirect_to action: "index"
  end

  private

    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :password)
    end

end

app/helpers/users_helper.rb
module UsersHelper

  include AdminHelper

  def all_users
    @users =User.all
  end

  def new_user
    @user = User.new
  end

  def create_user
    @user = User.new(user_params)
    @user.save
  end

  def find_user
    @user = User.find(params[:id])
  end

  def update_user
    @user.update(user_params)
  end

  def delete_user
    find_user
    @user.destroy
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name, :password)
    end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>

  <% if @user.admin %>
  <p>
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </p>

  <% end %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
<%= link_to 'All users', user_path %>
<%= link_to 'Destroy This Account', user_path(@user), method: :delete, data: { confirm: "Delete #{@user.username}?"}%>

app/views/users/index.html.erb
<h1>User List</h1>
<% @users.each do |user| %>
    <b><%=user.username%></b>
    <b><%= link_to "Edit", edit_user_path(user.id) %></b>
    <b><%=link_to 'Delete', user_path(user.id), method: :delete, data: { confirm: "Delete #{user.username}?"}%></b>
    <br>
<%end%>
    <br>
    <b><%= link_to "Add new user", new_user_path(:id) %></b>
    <br>
    <b><%= link_to "Cart_products", cart_products_path %></b>
    <br>
    <b><%= link_to "Carts", carts_path %></b>
    <br>
    <b><%= link_to "Categories", categories_path %></b>

app/views/users/new.html.erb
<h2>New User</h2>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show_old.html.erb
<% if @user.admin %>

      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="200" height="200">
        <div class="new-button">
          <button class="new-btn"> <a href="/products/new">New Product</a></button>
        </div>
  </div>
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="200" height="200">
    <div class="dropdown">
    <button onclick="showProductsMenu()" class="edit-btn" id="edit-product-button">Edit Product</button>
      <div id="edit-products-Dropdown" class="product-dropdown dropdown-content">
        <% @products.each do |product| %>
        <%= link_to product.name, product_path(id: product.id) %>
        <% end %>
      </div>
  </div>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="200" height="200">
  <div class="new-button">
          <button class="new-btn"> <a href="/categories/new">New Category</a></button>
        </div>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
<%end%>