config/routes.rb
Rails.application.routes.draw do
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'products#index'

  resources :users
  resources :categories
  resources :products
  resources :carts
  resources :cart_products

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_products
  has_many :products, through: :cart_products
  has_one :order

  def self.current(user_id)
  @cart = Cart.where(order_id: nil).find_by(user_id: user_id) || Cart.create(user_id: user_id)
  end

  def put_in (product_id)
    Product.find(product_id).add_to_cart(self.user_id)
  end

  def purchase
    order = Order.create(status: "pending", cart_id: @id)
    @order_id = order.id
    self.cart_products.each do |cart_product|
      cart_product.product.reserve_for_shipping(cart_product.quantity)
    end
  end

  def sub_total
    sum = 0
    self.cart_products.each do |item|
      sum += (item.quoted_price * item.quantity)
    end
    sum
  end

  def tax_amount
    sub_total * (try(self.user.addresses.find_by_address_type("home").state) || 0.075)
  end

  def shipping_cost
    self.cart_products.count * 1.50 #(try(self.user.get_a_shipping_cost) ||
  end

  def handling_charge
    2.00 || try(to_get_a_handling_charge)
  end

  def total
    sub_total + tax_amount + shipping_cost + handling_charge
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :logged_in?
  before_action :authorize, only: [:index]

  include CartsHelper

  def index
    all_carts
    puts @carts
  end

  def new
    new_cart
  end

  def create
    if create_cart
      redirect_to action: "index"
    else
      render 'new'
    end
  end

  def show
    find_cart
  end

  def edit
    find_cart
  end

  def update
    find_cart
    if update_cart
      redirect_to action: "index"
    else
      render 'edit'
    end
  end

  def destroy
    delete_cart
      redirect_to action: "index"
  end
end

app/helpers/carts_helper.rb
module CartsHelper

  def current_cart
    @cart = Cart.find_by_user_id(current_user.id) || create_cart
  end

  def all_carts
    @carts = Cart.all
  end

  def new_cart
    @cart = Cart.new
  end

  def create_cart
    @cart = Cart.new
    @cart.user_id = current_user.id
    @cart.save
  end

  def find_cart
    @cart = Cart.find(params[:id])
  end

  def update_cart
    @cart.update(cart_params)
  end

  def delete_cart
    find_cart
    @cart.destroy
  end

  private

    def cart_params
      return params.permit(:id, :user_id, :order_id) unless params[:cart]
      params.require(:cart).permit(:id, :user_id, :order_id)
    end

end

app/views/carts/_form.html.erb
<% @cart.cart_products.each do |cart_product| %>
    <a href="/products/<%=cart_product.product.id%>"><img src="<%=cart_product.product.image%>"></img></a><br>
    <b><%= link_to cart_product.product.name, product_path(id: cart_product.product.id) %></b>
    <br>
    <em>Price: $<%=cart_product.quoted_price%></em>
    <br>
    <em>Quantity: <%=cart_product.quantity%></em>
    <br>
    <b><%= link_to "Edit item", edit_cart_product_path(cart_product.id) %></b>
    <b><%=link_to 'Delete item', cart_product_path(cart_product.id), method: :delete, data: { confirm: "Delete #{cart_product.product.name}?"}%></b>
<%end%>

app/views/carts/edit.html.erb
<h1>Your Shopping Cart</h1>

<%= render 'form' %>

<br>
<%=link_to 'Delete Cart', cart_path, method: :delete, data: { confirm: "Delete #{@cart.id}?"}%>
<br>
<%= link_to 'Back', carts_path %>
<br>
<p>Total Cart Subtotal: $<%= current_cart.sub_total %></p>
<p>Total Cart Taxes: $<%= current_cart.tax_amount %></p>
<p>Total Cart Shipping: $<%= current_cart.shipping_cost %></p>
<p>Total Cart Handling: $<%= current_cart.handling_charge %></p>
<p>Total Cart Cost: $<%= current_cart.total %></p>

app/views/carts/index.html.erb
<% @carts.each do |cart| %>
    <b><%= link_to cart, cart_path(id: cart.id) %></b>
    <b><%= link_to "Edit", edit_cart_path(cart.id) %></b>
    <b><%=link_to 'Delete', cart_path(cart.id), method: :delete, data: { confirm: "Delete #{cart}?"}%></b>
    <br>    <br>
<%end%>

app/views/carts/show.html.erb
<%if @cart.products %>
<% @cart.products.each do |product| %>
  <div>
    <a href="/products/<%=product.id%>"><img src="<%=product.image%>"></img></a><br>
    <b><%= link_to product.name, product_path(id: product.id) %></b>
    <br>
    <em>$<%=product.price%>0</em>
  </div>
<%end%>
<%else%>
<h2>Your cart is empty! <a href="/">Shop here.</a><h2>
<%end%>