config/routes.rb
Rails.application.routes.draw do
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'products#index'

  resources :users
  resources :categories
  resources :products
  resources :carts
  resources :cart_products

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  include CategoriesHelper

  before_action :authorize

  def index
    all_categories
  end

  def new
    new_category
  end

  def create
    if create_category
      redirect_to action: "index"
    else
      render 'new'
    end
  end

  def show
    find_category
  end

  def edit
    find_category
  end

  def update
    find_category
    if update_category
      redirect_to index
    else
      render 'edit'
    end
  end

  def destroy
    delete_category
    redirect_to action: "index"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def all_categories
    @categories = Category.all
  end

  def displayed_categories
    @categories = Category.all
    @categories = Category.find(params[:category_id]) if params[:category_id]
  end

  def new_category
    @category = Category.new
  end

  def create_category
    @category = Category.new(category_params)
    @category.save
  end

  def find_category
    @category = Category.find(category_params[:id])
  end

  def update_category
    @category.update(category_params)
  end

  def delete_category
    find_category
    @category.destroy
  end

  private

    def category_params
      params.permit(:name, :id)
    end

end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing <%=@category.name%></h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>
<%=link_to 'Delete', category_path, method: :delete, data: { confirm: "Delete #{@category.name}?"}%>

app/views/categories/index.html.erb
<h1>Category List</h1>
<% @categories.each do |category| %>
    <b><%=category.name%></b>
    <b><%= link_to "Edit", edit_category_path(category.id) %></b>
    <b><%=link_to 'Delete', category_path(category.id), method: :delete, data: { confirm: "Delete #{category.name}?"}%></b>
    <br>
<%end%>
    <b><%= link_to "Add Category", new_category_path(:id) %></b>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>